name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
     runs-on: ubuntu-latest

     steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Setup Node.js
       uses: actions/setup-node@v2
       with:
         node-version: '16'
        
    - name: intall dependcies
       run: npm install

    - name: Generate the changelogs and release
      run: npm run release